// Demo-only stub. In a real Convex deployment, this file is generated by
// `npx convex dev` and contains typed function references for every mutation
// and query in `convex/`.

export const api = {
  analytics: {
    trackPricingPageView: "analytics:trackPricingPageView",
    trackUpgradeCtaClick: "analytics:trackUpgradeCtaClick",
    trackUpgradeCompleted: "analytics:trackUpgradeCompleted",
  },
  workflows: {
    createWorkflow: "workflows:createWorkflow",
    getWorkflow: "workflows:getWorkflow",
    listWorkflows: "workflows:listWorkflows",
    deleteWorkflow: "workflows:deleteWorkflow",
  },
  runs: {
    startRun: "runs:startRun",
    completeRun: "runs:completeRun",
    listRunsForWorkflow: "runs:listRunsForWorkflow",
    getRun: "runs:getRun",
  },
} as const;
